/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aprioricafe.gui.salesinvoice;

import com.aldoapp.swingboot.AppSession;
import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.helpers.RupiahHelper;
import com.aldoapp.swingboot.helpers.TimeHelper;
import com.aprioricafe.entities.CustomerPayment;
import com.aprioricafe.entities.PaymentMethod;
import com.aprioricafe.entities.SalesInvoice;
import com.aprioricafe.entities.SalesInvoiceStatus;
import com.aprioricafe.repositories.CustomerPaymentRepository;
import com.aprioricafe.repositories.SalesInvoiceRepository;
import com.aprioricafe.services.SalesInvoiceService;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentListener;
import javax.swing.text.PlainDocument;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

/**
 *
 * @author aldo
 */
public class PaymentDlg extends javax.swing.JDialog {
    @Autowired
    AppSession appSession;
    
    @Autowired
    CustomerPaymentRepository customerPaymentRepository;
    
    @Autowired
    SalesInvoiceRepository salesInvoiceRepository;
    
    @Autowired
    SalesInvoiceService salesInvoiceSvc;
    
    private SalesInvoice salesInvoice;
    
    private CustomerPayment entity;
    
    BigDecimal discountAmount;
    BigDecimal grandTotal;
    BigDecimal amountPaid;
    
   
    BigDecimal change;
    
    /**
     * Creates new form PaymentDlg
     */
    public PaymentDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
        
        discountAmount = BigDecimal.ZERO;
        grandTotal = BigDecimal.ZERO;
        amountPaid = BigDecimal.ZERO;
        change = BigDecimal.ZERO;
        
        PlainDocument doc = (PlainDocument) txtDiscountAmount.getDocument();        
        var c = calculateTotalFunc();
        doc.addDocumentListener(c);
        
        PlainDocument doc2 = (PlainDocument) txtTotalPaid.getDocument();        
        var c2 = calculateChangeFunc();
        doc2.addDocumentListener(c2);
        
    }
    
    DocumentListener calculateTotalFunc(){
        return new DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent de) {
                calculateTotal();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent de) {
                calculateTotal();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent de) {
                calculateTotal();
            }
          };
    }
     DocumentListener calculateChangeFunc(){
        return new DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent de) {
                calculateTotal();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent de) {
                calculateTotal();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent de) {
                calculateTotal();
            }
          };
    }
    
    
    void calculateTotal(){
        
        String tdiscountAmount = txtDiscountAmount.getText();
        if(!tdiscountAmount.isBlank()){
            discountAmount = new BigDecimal(tdiscountAmount);
        }
        //grandTotal = salesInvoice.getTotalAmount().subtract(discountAmount);
        grandTotal = salesInvoice.getNetDue().subtract(discountAmount);
        lblGrandTotal.setText(RupiahHelper.formatRupiah(grandTotal));
                
        amountPaid = BigDecimal.ZERO;
        String tamountPaid = txtTotalPaid.getText();
        if(!tamountPaid.isBlank()){
            amountPaid = new BigDecimal(tamountPaid);
        }
        change = amountPaid.subtract(grandTotal);
        lblChange.setText(RupiahHelper.formatRupiah(change));
    }
    
    private void txtDiscountAmountActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }//G
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiscountAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTotalPaid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblGrandTotal = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Total");

        lblTotalAmount.setText("0");

        jLabel4.setText("Potongan");

        txtDiscountAmount.setText("0");
        txtDiscountAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountAmountActionPerformed(evt);
            }
        });

        jLabel5.setText("Harus Bayar");

        jLabel6.setText("Pembayaran");

        txtTotalPaid.setText("0");
        txtTotalPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPaidActionPerformed(evt);
            }
        });

        jLabel7.setText("Kembalian");

        btnSave.setText("Proses");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblGrandTotal.setText("0");

        lblChange.setText("0");

        jLabel1.setText("Rp.");

        jLabel8.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalAmount)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPaid))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGrandTotal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancel))
                                    .addComponent(lblChange))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotalAmount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiscountAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblGrandTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblChange))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtTotalPaidActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }
    public static SalesInvoice showModal(SalesInvoice xsalesInvoice) {
        
        PaymentDlg dialog = new PaymentDlg();
        
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setTitle("Pembayaran");
           
        dialog.salesInvoice = xsalesInvoice;
        
        //dialog.lblTotalAmount.setText(RupiahHelper.formatRupiah(xsalesInvoice.getTotalAmount()));                        
        dialog.lblTotalAmount.setText(RupiahHelper.formatRupiah(xsalesInvoice.getNetDue()));         
        if(xsalesInvoice.getStatus() == SalesInvoiceStatus.UNPAID.getValue()){//first payment
            
        }else{
            
        }
        dialog.calculateTotal();
        
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        return dialog.salesInvoice;
        //System.exit(0);
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        var success = savePayment();
        if(success){
            dispose();    
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed
    
    @Transactional
    boolean savePayment(){        
        if(salesInvoice.getStatus() == SalesInvoiceStatus.UNPAID.getValue()){//first payment
            salesInvoice.setTotalPaid(amountPaid);
            salesInvoice.setDiscountAmount(discountAmount);
            salesInvoice.setGrandTotal(grandTotal);
            var savedSalesInvoice = salesInvoiceSvc.calculatePayments(salesInvoice);
            if(savedSalesInvoice!=null){
                return true;
            }else{
                JOptionPane.showMessageDialog(null, "Data Sales Invoice Tidak Tersimpan");    
            }
        }else{
         //save payment
            if(entity==null){
                entity = new CustomerPayment();
            }        
            entity.setCreatedAt(TimeHelper.getCurrentTimestamp());
            entity.setCreatedBy(appSession.getCurrentuser());
            entity.setTotalAmount(salesInvoice.getTotalAmount());
            entity.setDiscountAmount(discountAmount);
            entity.setGrandTotal(grandTotal);
            if(change.compareTo(BigDecimal.ZERO)<0){//kurang
                entity.setTotalPaid(amountPaid);    
            }else{
                entity.setTotalPaid(grandTotal);    
            }

            entity.setRealTotalPaid(amountPaid);
            entity.setPaymentMethod(PaymentMethod.CASH.getStringValue());        
            entity.setChangeAmount(change);
            entity.setSalesInvoice(salesInvoice);
            //update sales invoice
            //save 
            var saved = customerPaymentRepository.save(entity);
            if(saved!=null){
                var savedSalesInvoice = salesInvoiceSvc.calculatePayments(salesInvoice);
                if(savedSalesInvoice!=null){
                    return true;
                }else{
                    JOptionPane.showMessageDialog(null, "Data Sales Invoice Tidak Tersimpan");    
                }
            }else{
                JOptionPane.showMessageDialog(null, "Data Pembayaran Tidak Tersimpan");    

            }         
        }
        return false;
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTextField txtDiscountAmount;
    private javax.swing.JTextField txtTotalPaid;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the entity
     */
    public CustomerPayment getEntity() {
        return entity;
    }

    /**
     * @param entity the entity to set
     */
    public void setEntity(CustomerPayment entity) {
        this.entity = entity;
    }
}
