/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.aprioricafe.gui.salesinvoice;

import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.helpers.RupiahHelper;
import com.aprioricafe.dto.SalesInvoiceDetailsReportItem;
import com.aprioricafe.entities.SalesInvoice;
import com.aprioricafe.entities.SalesInvoiceItem;
import com.aprioricafe.repositories.MenuRepository;
import com.aprioricafe.repositories.SalesInvoiceItemRepository;
import com.aprioricafe.services.PrintSalesInvoiceReportService;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author aldo
 */
public class SalesInvoiceDetailDlg extends javax.swing.JDialog {
    @Autowired
    MenuRepository menuRepository;
    
    @Autowired
    SalesInvoiceItemRepository salesInvoiceItemRepository;
    
    @Autowired
    PrintSalesInvoiceReportService printSalesInvoiceReportService;
    
    SalesInvoice salesInvoice;
    
    private List<SalesInvoiceItem> items = new ArrayList<>();
    
    List<SalesInvoiceDetailsReportItem> reportItems = new ArrayList<>();
    
    /** Creates new form SalesInvoiceDetailDlg */
    public SalesInvoiceDetailDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
        loadData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblInvoiceNo = new javax.swing.JLabel();
        txsds = new javax.swing.JLabel();
        lblInvoiceDateTime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblAmountPaid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDiscountAmount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Nota Penjualan");

        jLabel1.setText("Nomor Nota");

        lblInvoiceNo.setText("-");

        txsds.setText("Waktu");

        lblInvoiceDateTime.setText("----");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jLabel2.setText("Menu");

        btnPrint.setText("Cetak");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel3.setText("Total Pembayaran");

        lblAmountPaid.setText("0");

        jLabel4.setText("Total");

        lblTotalAmount.setText("0");

        jLabel5.setText("Potongan");

        lblDiscountAmount.setText("0");

        jLabel6.setText("Harus Bayar");

        lblGrandTotal.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txsds))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInvoiceDateTime)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblInvoiceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnPrint)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmountPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiscountAmount)
                                    .addComponent(lblTotalAmount)
                                    .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblInvoiceNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txsds)
                    .addComponent(lblInvoiceDateTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTotalAmount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDiscountAmount))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblGrandTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAmountPaid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try{
            printSalesInvoiceReportService.generateAndPrint(lblInvoiceDateTime.getText(),lblInvoiceNo.getText(), lblTotalAmount.getText(),reportItems);
        }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    public static void showModal(SalesInvoice salesInvoice) {
        Locale locale = new Locale("in", "ID");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy").withLocale(locale);
        String formattedDate = salesInvoice.getDate().format(formatter);
        SalesInvoiceDetailDlg dialog = new SalesInvoiceDetailDlg();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.salesInvoice = salesInvoice;
        dialog.lblInvoiceNo.setText(salesInvoice.getInvoiceNo());
        dialog.lblInvoiceDateTime.setText(formattedDate);
        dialog.lblAmountPaid.setText(RupiahHelper.formatRupiah(salesInvoice.getTotalPaid().add(salesInvoice.getOtherPayment())));
        dialog.lblTotalAmount.setText(RupiahHelper.formatRupiah(salesInvoice.getTotalAmount()));
        dialog.lblDiscountAmount.setText(RupiahHelper.formatRupiah(salesInvoice.getDiscountAmount()));
        dialog.lblGrandTotal.setText(RupiahHelper.formatRupiah(salesInvoice.getGrandTotal()));
        dialog.loadItems(salesInvoice);
        dialog.loadData();
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        //System.exit(0);
    }
    public void loadItems(SalesInvoice invoice){
        this.items = salesInvoiceItemRepository.findAllByInvoiceId(invoice.getId());
        
    }
    
    private void loadData(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Kode Menu");        
        tableModel.addColumn("Nama Menu");
        tableModel.addColumn("Kategori");
        tableModel.addColumn("Harga");
        tableModel.addColumn("Qty");
        tableModel.addColumn("Sub Total");
        
        reportItems.clear();
        
        if(items!=null){
            for(SalesInvoiceItem item: items){
                Vector row = new Vector();
                var menu = item.getMenu();
                row.add(menu.getCode());
                row.add(menu.getName());
                row.add(menu.getCategory());
                var tunitprice = RupiahHelper.formatRupiah(menu.getUnitPrice());
                row.add(tunitprice);
                row.add(item.getQuantity());
                var subtotal = menu.getUnitPrice().multiply(new BigDecimal(item.getQuantity()));
                var tsubtotal = RupiahHelper.formatRupiah(subtotal);
                row.add(tsubtotal);
                tableModel.addRow(row);
                
                //report 
                SalesInvoiceDetailsReportItem reportItem = new SalesInvoiceDetailsReportItem();
                reportItem.setMenuCode(menu.getCode());
                reportItem.setMenuName(menu.getName());
                reportItem.setQty(String.valueOf(item.getQuantity()));
                reportItem.setSubTotal(tsubtotal);
                reportItem.setUnitPrice(tunitprice);
                reportItems.add(reportItem);
                
            }
        }
        
        tbl.setModel(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmountPaid;
    private javax.swing.JLabel lblDiscountAmount;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblInvoiceDateTime;
    private javax.swing.JLabel lblInvoiceNo;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTable tbl;
    private javax.swing.JLabel txsds;
    // End of variables declaration//GEN-END:variables

}
