/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aprioricafe.gui.salesinvoice;

import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.helpers.RupiahHelper;
import com.aprioricafe.entities.SalesInvoice;
import com.aprioricafe.entities.SalesInvoiceStatus;
import com.aprioricafe.repositories.SalesInvoiceRepository;
import com.aprioricafe.services.SalesInvoiceService;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author aldo
 */
public class SalesInvoiceList extends javax.swing.JPanel {
    @Autowired
    SalesInvoiceService salesInvoiceSvc;
    
    @Autowired
    SalesInvoiceRepository salesInvoiceRepository;
    
    Long selectedID;
    /**
     * Creates new form SalesInvoiceList
     */
    public SalesInvoiceList() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        Locale locale = new Locale("in", "ID");

        startDate.setLocale(locale);
        startDate.setDateToToday();
        
        endDate.setLocale(locale);
        endDate.setDateToToday();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel3 = new javax.swing.JLabel();
        endDate = new com.github.lgooddatepicker.components.DatePicker();
        btnSearch = new javax.swing.JButton();
        btnViewDetail = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jLabel1.setText("Daftar Penjualan");

        jLabel2.setText("Mulai Tanggal");

        jLabel3.setText("Sampai Tanggal");

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewDetail.setText("Lihat Detail Nota");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        btnPay.setText("Bayar");
        btnPay.setActionCommand("Bayar");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnViewDetail)
                                .addGap(18, 18, 18)
                                .addComponent(btnPay)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetail)
                    .addComponent(btnPay))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
        int row = tbl.getSelectedRow();
        if(row==-1){
            return;
        }
        selectedID = Long.valueOf(tbl.getModel().getValueAt(row, 0).toString());
        var entityx = salesInvoiceRepository.findById(selectedID);
        if(entityx.isPresent()){
            SalesInvoiceDetailDlg.showModal(entityx.get());
            loadData();
        }
        
    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        int row = tbl.getSelectedRow();
        if(row==-1){
            return;
        }
        selectedID = Long.valueOf(tbl.getModel().getValueAt(row, 0).toString());
        var entityx = salesInvoiceRepository.findById(selectedID);
        if(entityx.isPresent()){
            PaymentDlg.showModal(entityx.get());
            loadData();
        }
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadData();
    }//GEN-LAST:event_btnSearchActionPerformed
    private void loadData(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");
        tableModel.addColumn("Nomor Nota");
        tableModel.addColumn("Tanggal");
        tableModel.addColumn("Total");
        tableModel.addColumn("Status");
        Locale locale = new Locale("in", "ID");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy").withLocale(locale);
        
        Iterable<SalesInvoice> idetails = salesInvoiceRepository.findAllByInvoiceDateBetween(startDate.getDate(), endDate.getDate());
        for (SalesInvoice detail : idetails) {
            Vector row = new Vector();
            
            String formattedDate = detail.getDate().format(formatter);
            row.add(detail.getId());
            row.add(detail.getInvoiceNo());    
            row.add(formattedDate);
           
            row.add(RupiahHelper.formatRupiah(detail.getGrandTotal()));
            
            String status = "";
            var istatus = detail.getStatus();
            if(SalesInvoiceStatus.FULL_PAID.getValue() == istatus){                
                status = "Lunas";                    
            }else if(SalesInvoiceStatus.PARTIALLY_PAID.getValue() == istatus){                
                status = "Dibayar Sebagian";                    
            }else if(SalesInvoiceStatus.UNPAID.getValue() == istatus){                
                status = "Belum dibayar";                    
            }
            row.add(status);
            
            tableModel.addRow(row);
                        
        }
        
        tbl.setModel(tableModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetail;
    private com.github.lgooddatepicker.components.DatePicker endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.github.lgooddatepicker.components.DatePicker startDate;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
