/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aprioricafe.gui.user;

import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.entities.Role;
import com.aldoapp.swingboot.entities.RoleAccess;
import com.aldoapp.swingboot.gui.ComboItem;
import com.aldoapp.swingboot.repositories.RoleAccessRepository;
import com.aldoapp.swingboot.repositories.RoleRepository;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

/**
 *
 * @author koplog
 */
public class RoleAccessDlg extends javax.swing.JDialog {
    @Autowired
    RoleRepository roleRepository;
    
    @Autowired
    RoleAccessRepository roleAccessRepository;
    
    /**
     * Creates new form RoleAccessDlg
     */
    public RoleAccessDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
        loadRoles();
        loadRoleAccess();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbPurchaseOrder = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cbSalesInvoice = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cbProducts = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        cbMember = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        cbUser = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hak Akses Role");

        jLabel1.setText("Role");

        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });

        jLabel2.setText("Hak Akses");

        jLabel3.setText("Transaksi");

        jLabel4.setText("Pembelian");

        cbPurchaseOrder.setText("Yes");
        cbPurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPurchaseOrderActionPerformed(evt);
            }
        });

        jLabel5.setText("Penjualan");

        cbSalesInvoice.setText("Yes");
        cbSalesInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalesInvoiceActionPerformed(evt);
            }
        });

        jLabel6.setText("Data Barang");

        cbProducts.setText("Yes");
        cbProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductsActionPerformed(evt);
            }
        });

        jLabel7.setText("Member");

        cbMember.setText("Yes");
        cbMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMemberActionPerformed(evt);
            }
        });

        jLabel8.setText("User");

        cbUser.setText("Yes");
        cbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUserActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUser)
                            .addComponent(cbMember)
                            .addComponent(cbProducts)
                            .addComponent(cbSalesInvoice)
                            .addComponent(cbPurchaseOrder))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbPurchaseOrder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbSalesInvoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbProducts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPurchaseOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPurchaseOrderActionPerformed

    private void cbSalesInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalesInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSalesInvoiceActionPerformed

    private void cbProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProductsActionPerformed

    private void cbMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMemberActionPerformed

    private void cbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUserActionPerformed
    
    @Transactional
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ComboItem ci = (ComboItem)cbRole.getSelectedItem();
        if(ci==null){
            return;
        }
        //delete first
        Role role = (Role)ci.getEntity();
        List<RoleAccess> existing = roleAccessRepository.findAllByRoleId(role.getId());
        for(RoleAccess ra: existing){
            roleAccessRepository.deleteById(ra.getId());
        }
        //save new values
        
        RoleAccess purchaseOrder = new RoleAccess();
        purchaseOrder.setMenu("PurchaseOrder");
        purchaseOrder.setRole(role);
        purchaseOrder.setHasAccess(cbPurchaseOrder.isSelected());
        roleAccessRepository.save(purchaseOrder);
        
        RoleAccess salesInvoice = new RoleAccess();
        salesInvoice.setMenu("SalesInvoice");
        salesInvoice.setRole(role);
        salesInvoice.setHasAccess(cbSalesInvoice.isSelected());
        roleAccessRepository.save(salesInvoice);
        
        RoleAccess products = new RoleAccess();
        products.setMenu("Products");
        products.setRole(role);
        products.setHasAccess(cbProducts.isSelected());
        roleAccessRepository.save(products);
        
        RoleAccess member = new RoleAccess();
        member.setMenu("Member");
        member.setRole(role);
        member.setHasAccess(cbMember.isSelected());
        roleAccessRepository.save(member);
        
        RoleAccess user = new RoleAccess();
        user.setMenu("User");
        user.setRole(role);
        user.setHasAccess(cbUser.isSelected());
        roleAccessRepository.save(user);
        
        JOptionPane.showMessageDialog(null, "Data Tersimpan. Restart supaya ngefek"); 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        loadRoleAccess();
    }//GEN-LAST:event_cbRoleActionPerformed
    void loadRoleAccess(){
        ComboItem ci = (ComboItem)cbRole.getSelectedItem();
        if(ci==null){
            return;
        }
        //delete first
        Role role = (Role)ci.getEntity();
        
        List<RoleAccess> roleAccesses = roleAccessRepository.findAllByRoleId(role.getId());
        for(RoleAccess access: roleAccesses){
            if(access.getMenu().equals("PurchaseOrder")){
                cbPurchaseOrder.setSelected(access.isHasAccess());               
            }else if(access.getMenu().equals("SalesInvoice")){
                cbSalesInvoice.setSelected(access.isHasAccess());               
            }else if(access.getMenu().equals("Products")){
                cbProducts.setSelected(access.isHasAccess());               
            }else if(access.getMenu().equals("Member")){
                cbMember.setSelected(access.isHasAccess());               
            }else if(access.getMenu().equals("User")){
                cbUser.setSelected(access.isHasAccess());               
            }
        }
    }
    public static void showModal(String[] args) {
        
        RoleAccessDlg dialog = new RoleAccessDlg();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        //System.exit(0);
    }
    
    private void loadRoles(){
        Iterable<Role> entites = roleRepository.findAll();
        cbRole.removeAllItems();
        for (Role entity : entites) {
            if(entity.getId()==Role.ADMIN.longValue()){
                continue;
            }
            cbRole.addItem(new ComboItem(entity.getName(), entity.getName(), entity));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox cbMember;
    private javax.swing.JCheckBox cbProducts;
    private javax.swing.JCheckBox cbPurchaseOrder;
    private javax.swing.JComboBox cbRole;
    private javax.swing.JCheckBox cbSalesInvoice;
    private javax.swing.JCheckBox cbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
