/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.aprioricafe.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class DashboardPanel extends javax.swing.JPanel {
    JLabel lblImage = new JLabel();
    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        setLayout(new BorderLayout());
        loadData();
        
        //setOpaque(true);
    }
    public void hideImage(){
        lblImage.setVisible(false);
    }
    public void showImage(){
        lblImage.setVisible(true);
    }
    void loadData(){
        try{
            
            File dest = new File("images"+File.separator+"background.png");

            Image image = ImageIO.read(dest);
            if (image != null) {                
                lblImage.setIcon(new ImageIcon(image));
                Dimension size = new Dimension(image.getWidth(null), image.getHeight(null));
                lblImage.setPreferredSize(size);
                lblImage.setMinimumSize(size);
                lblImage.setMaximumSize(size);
                lblImage.setSize(size);
                //lblImage.setOpaque(true);
                
                add(lblImage,BorderLayout.CENTER);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
