/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldoapp.swingboot.gui;


import com.aldoapp.swingboot.AppSession;
import com.aldoapp.swingboot.BeanProvider;

import com.aldoapp.swingboot.entities.User;
import com.aldoapp.swingboot.gui.setting.CompanyDlg;
import com.aldoapp.swingboot.gui.setting.SettingsDlg;
import com.aldoapp.swingboot.gui.user.UserManagement;

import com.aldoapp.swingboot.services.InitialDataService;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Insets;
import java.awt.event.ContainerEvent;
import java.awt.event.ContainerListener;
import java.io.File;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JLayer;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author aldo
 */

public class MainFrame extends javax.swing.JFrame {
    @Autowired
    AppSession appSession;
    
    @Autowired
    InitialDataService initialDataSvc;
    
    
    
    private User user;
    private boolean isAdmin = false;
    private JTabbedPane tabbedPane;
    private JLabel lblUser;
    private HashMap<String,JPanel> openTabs = new HashMap<>();
    

    /**
     * Creates new form MainFrame
     */
    public JComponent makeUI() {
        UIManager.put("TabbedPane.tabInsets", new Insets(2, 2, 2, 50));
        JPanel p = new JPanel(new BorderLayout());
        ImagePanel panel = new ImagePanel(new ImageIcon("images"+File.separator+"background.png").getImage());
        tabbedPane = new JTabbedPane();
        tabbedPane.addContainerListener(new ContainerListener() {
            @Override
            public void componentAdded(ContainerEvent e) {
                // Do nothing when a component is added to the tabbed pane
                p.remove(panel);
            }

            @Override
            public void componentRemoved(ContainerEvent e) {
                // Get the removed component (tab) from the event
                Component removedComponent = e.getChild();
                System.out.println("Tab removed: " + removedComponent);
                openTabs.values().remove((JPanel)removedComponent);
                // Do your processing here with the removed tab.
                if(openTabs.isEmpty()){
                    p.add(panel);
                }
            }
        });
        

        
        p.add(panel);
        p.add(new JLayer<JTabbedPane>(tabbedPane, new CloseableTabbedPaneLayerUI()));
        JPanel statusPanel = new JPanel();
        statusPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
        statusPanel.setBorder(new BevelBorder(BevelBorder.LOWERED));
        p.add(statusPanel, BorderLayout.SOUTH);
        
        lblUser = new JLabel("status");
        lblUser.setHorizontalAlignment(SwingConstants.LEFT);
        statusPanel.add(lblUser);
        
        //return p;
        return p;
      }
    
     void addTab(String title, JPanel panel){
        if(openTabs.containsKey(title)){
            var pnl = openTabs.get(title);
            tabbedPane.setSelectedComponent(pnl);
        }else{
            tabbedPane.addTab( title, panel);    
            tabbedPane.setSelectedComponent(panel);
            
            openTabs.put(title, panel);
        }
        
        
    }
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame()  {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnUser = new javax.swing.JMenuItem();
        mnCompanySetting = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnListInvoice = new javax.swing.JMenuItem();
        mnAddInvoice = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Invoice");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rootPanel.setName("rootPanel"); // NOI18N

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        mnUser.setText("Users");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        jMenu1.add(mnUser);

        mnCompanySetting.setText("Company");
        mnCompanySetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCompanySettingActionPerformed(evt);
            }
        });
        jMenu1.add(mnCompanySetting);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Invoices");

        mnListInvoice.setText("Daftar Invoice");
        mnListInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnListInvoiceActionPerformed(evt);
            }
        });
        jMenu2.add(mnListInvoice);

        mnAddInvoice.setText("Tambah Invoice");
        mnAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAddInvoiceActionPerformed(evt);
            }
        });
        jMenu2.add(mnAddInvoice);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        // TODO add your handling code here:
        if(!isAdmin){
            JOptionPane.showMessageDialog(null, "Access Denied");
            return;
        }
        UserManagement.showModal(null);
    }//GEN-LAST:event_mnUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            initialDataSvc.checkFolders();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        if(initialDataSvc.isFirstRun()){
            SettingsDlg.showModal(null);
        }else{
            LoginDlg.showModal(null);
            user = appSession.getCurrentuser();
            if(user==null){
                dispose();
            }else{
               isAdmin = appSession.isAdmin();
               
            }
        }
    }//GEN-LAST:event_formWindowOpened
    
    private void mnCompanySettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCompanySettingActionPerformed
        // TODO add your handling code here:
        if(!isAdmin){
            JOptionPane.showMessageDialog(null, "Access Denied");
            return;
        }
        CompanyDlg.showModal(null);
    }//GEN-LAST:event_mnCompanySettingActionPerformed

    private void mnListInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnListInvoiceActionPerformed
        
    }//GEN-LAST:event_mnListInvoiceActionPerformed

    private void mnAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAddInvoiceActionPerformed
        
        
        
    }//GEN-LAST:event_mnAddInvoiceActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAddInvoice;
    private javax.swing.JMenuItem mnCompanySetting;
    private javax.swing.JMenuItem mnListInvoice;
    private javax.swing.JMenuItem mnUser;
    public javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables
}
