/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aprioricafe.gui.item;

import com.aldoapp.swingboot.AppSession;
import com.aldoapp.swingboot.BeanProvider;
import com.aprioricafe.entities.Item;
import com.aprioricafe.repositories.ItemRepository;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author aldo
 */
public class AddItemQtyDlg extends javax.swing.JDialog {
    @Autowired
    AppSession appSession;
    
    @Autowired
    ItemRepository itemRepository;
    
    private Item selectedItem;
    /**
     * Creates new form AddItemDlg
     */
    public AddItemQtyDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
        
        Action action = new AbstractAction()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                doSearchCode();
            }
        };

        txtCode.addActionListener(action);
        txtAddAmount.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              warn();
            }
            public void removeUpdate(DocumentEvent e) {
              warn();
            }
            public void insertUpdate(DocumentEvent e) {
              warn();
            }

            public void warn() {
                var tx = txtAddAmount.getText().trim();
                if(tx.isBlank()){
                    return;
                }
                var add  =Integer.parseInt(tx);
               if (add<=0){
                 JOptionPane.showMessageDialog(null,
                    "Error: Please enter number bigger than 0", "Error Message",
                    JOptionPane.ERROR_MESSAGE);
               }else{
                   var currqty = Long.valueOf(0);
                   if(selectedItem.getStock()!=null){
                       currqty = selectedItem.getStock();
                   }
                   var newqty = currqty +add;
                   lblTotal.setText(String.valueOf(newqty));
               }
            }
        });
    }
    void doSearchCode(){
        var text = txtCode.getText().trim();
        if(text.length()>0){
            Optional<Item> xproduct = itemRepository.findByCode(text);
            if(xproduct.isPresent()){
                selectedItem = xproduct.get();
                lblName.setText(selectedItem.getName());
                lblUnit.setText(selectedItem.getUnitName());
                lblAmount.setText(selectedItem.getStock().toString());
            }else{
                JOptionPane.showMessageDialog(null, "Kode Barang tidak ditemukan"); 
            }
        }else{
            JOptionPane.showMessageDialog(null, "Masukkan kode barang"); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAddAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblUnit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengadaan Barang");

        jLabel1.setText("Kode Barang");

        btnSearch.setText("Cari");
        btnSearch.setToolTipText("");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Barang");

        lblName.setText("-");

        jLabel3.setText("Jumlah");

        lblAmount.setText("-");

        jLabel4.setText("Tambahan");

        txtAddAmount.setText("0");

        jLabel5.setText("Total");

        lblTotal.setText("0");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUnit))
                            .addComponent(txtAddAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAmount)
                    .addComponent(lblUnit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
        dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        doSearchCode();
    }//GEN-LAST:event_btnSearchActionPerformed

    public static void showModal(String[] args) {
        
        AddItemQtyDlg dialog = new AddItemQtyDlg();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        //System.exit(0);
    }
    
    private boolean save(){
        if(!validateInputs()){
            return false;
        }
        var prev = Long.valueOf(0);
        if(selectedItem.getStock()!=null){
            prev = selectedItem.getStock();
        }
        var increase = Long.valueOf(txtAddAmount.getText());
        var newqty = prev+increase;
        selectedItem.setStock(newqty);
        var savedEntity = itemRepository.saveAndFlush(selectedItem);
        if(savedEntity!=null){
            selectedItem = savedEntity;           
            JOptionPane.showMessageDialog(null, "Data Tersimpan"); 
            clearFields();
            return true;
        }else{
            JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            return false;
        }
    }
    private void clearFields() {
        
        txtAddAmount.setText("");
        txtCode.setText("");
        lblName.setText("");       
        lblAmount.setText("");       
        lblUnit.setText("");
        lblTotal.setText("");

    }
    private boolean validateInputs(){
        boolean res = true;        
        
        List<String> errors = new ArrayList();
        if(txtAddAmount.getText().trim().length()==0){
            errors.add("Masukkan quantity");            
        }
        if(txtCode.getText().trim().length()==0){
            errors.add( "Masukkan kode");                    
        }
        if(selectedItem==null){
            errors.add( "Masukkan item");            
        }
        
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(null, String.join("\n", errors));
            return false;
        }
        return res;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JTextField txtAddAmount;
    private javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
