/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aprioricafe.gui.item;

import com.aldoapp.swingboot.AppSession;
import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.gui.ComboItem;
import com.aldoapp.swingboot.helpers.TimeHelper;
import com.aprioricafe.entities.Item;
import com.aprioricafe.repositories.ItemRepository;
import com.privatejgoodies.forms.layout.ConstantSize.Unit;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

/**
 *
 * @author aldo
 */
public class ItemDlg extends javax.swing.JDialog {
    @Autowired
    AppSession appSession;
    
    @Autowired
    ItemRepository itemRepository;
    /**
     * @return the entity
     */
    public Item getEntity() {
        return entity;
    }

    /**
     * @param entity the entity to set
     */
    public void setEntity(Item entity) {
        this.entity = entity;
    }
    private Item entity;
    /**
     * Creates new form ItemDlg
     */
    public ItemDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUnitName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel3.setText("Satuan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave)
                    .addComponent(txtCode)
                    .addComponent(txtName)
                    .addComponent(txtUnitName, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    @Transactional
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        var res = save();
        if(!res){
            return;
        }
        int dialogResult = JOptionPane.showConfirmDialog (null, "Apakah anda mau input data lagi?","Confirmation",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            dispose();
            ItemDlg.showModal(null);
        }else{
            dispose();
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed
    private boolean save(){
        if(!validateInputs()){
            return false;
        }
        if(entity==null){
            setEntity(new Item());
            entity.setCreatedAt(TimeHelper.getCurrentTimestamp());
            entity.setCreatedBy(appSession.getCurrentuser());
        }else{
            entity.setUpdatedAt(TimeHelper.getCurrentTimestamp());            
            entity.setUpdatedBy(appSession.getCurrentuser());
        }
        
        entity.setCode(txtCode.getText().trim());
        entity.setName(txtName.getText().trim());
        entity.setUnitName(txtUnitName.getText().trim());
        var savedEntity = itemRepository.saveAndFlush(entity);
        if(savedEntity!=null){
            setEntity(savedEntity);
            
            JOptionPane.showMessageDialog(null, "Data Tersimpan"); 
            clearFields();
            return true;
        }else{
            JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            return false;
        }
    }
    public static Item showModal(Item currentItem) {
        ItemDlg dialog = new ItemDlg();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setTitle("Tambah Barang");
        if(currentItem!=null){
            dialog.setTitle("Edit Barang");
            dialog.setEntity(currentItem);
            dialog.txtCode.setText(currentItem.getCode());
            dialog.txtName.setText(currentItem.getName());
            dialog.txtUnitName.setText(currentItem.getUnitName());
            
        }
        
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        return dialog.getEntity();
    }
    
    private boolean validateInputs(){
        boolean res = true;        
        
        List<String> errors = new ArrayList();
        if(txtName.getText().trim().length()==0){
            errors.add("Masukkan nama");            
        }
        if(txtCode.getText().trim().length()==0){
            errors.add( "Masukkan kode");                    
        }
        if(txtUnitName.getText().trim().length()==0){
            errors.add( "Masukkan satuan");            
        }
        
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(null, String.join("\n", errors));
            return false;
        }
        return res;
    }
    private void clearFields() {
        
        txtName.setText("");
        txtCode.setText("");
        txtUnitName.setText("");       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUnitName;
    // End of variables declaration//GEN-END:variables
}
