/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldoapp.swingboot.gui.setting;

import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.entities.Role;
import com.aldoapp.swingboot.entities.Setting;
import com.aldoapp.swingboot.entities.User;
import com.aldoapp.swingboot.gui.ComboItem;
import com.aldoapp.swingboot.gui.ImageFileSelector;
import com.aldoapp.swingboot.helpers.TimeHelper;
import com.aldoapp.swingboot.repositories.SettingRepository;
import com.aldoapp.swingboot.services.InitialDataService;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author aldo
 */
public class CompanyDlg extends javax.swing.JDialog {
    @Autowired
    SettingRepository settingRepository;
    
    @Autowired
    InitialDataService initialDataService;
    /**
     * Creates new form CompanyDlg
     */
    public CompanyDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Profile Perusahaan");

        jLabel1.setText("Nama Perusahaan");

        txtCompanyName.setName("txtCompanyName"); // NOI18N

        txtAddress.setName("txtUsername"); // NOI18N

        jLabel2.setText("Alamat");

        jLabel3.setText("No Telp");

        txtPhone.setName("txtUsername"); // NOI18N

        jLabel4.setText("Logo");

        imgLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLogoMouseClicked(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(489, 489, 489))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPhone)
                            .addComponent(txtCompanyName)
                            .addComponent(txtAddress))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseClicked
        // TODO add your handling code here:
        try{
            File logoFile = ImageFileSelector.showDialog(null);
            if(logoFile==null){
                return;
            }
            String docPath = initialDataService.getDocPath();            
            File dest = new File(docPath+File.separator+"logo.png");

            Files.copy(logoFile.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);

            Image image = ImageIO.read(dest);
            if (image != null) {
                imgLogo.setIcon(new ImageIcon(image));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_imgLogoMouseClicked
    public static void showModal(String[] args) {
        
        CompanyDlg dialog = new CompanyDlg();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        //System.exit(0);
    }
    
    private boolean validateInputs(){
        boolean res = true;
        
        List<String> errors = new ArrayList();
        if(txtCompanyName.getText().trim().length()==0){
            errors.add("Masukkan nama perusahaan");            
        }
        if(txtAddress.getText().trim().length()==0){
            errors.add( "Masukkan alamat perusahaan");            
        }
        if(txtPhone.getText().trim().length()==0){
            errors.add( "Masukkan telepon perusahaan");            
        }
        
       
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(null, String.join("\n", errors));
            return false;
        }
        
        return res;
    }
    
    private void loadData(){
        var xComp = settingRepository.findByKey(Setting.COMPANY_NAME);
        if(xComp.isPresent()){
            txtCompanyName.setText(xComp.get().getValue());
        }
        var xCompAdd = settingRepository.findByKey(Setting.COMPANY_ADDRESS);
        if(xCompAdd.isPresent()){
            txtAddress.setText(xCompAdd.get().getValue());            
        }
        var xCompPhone = settingRepository.findByKey(Setting.COMPANY_PHONE);
        if(xCompPhone.isPresent()){
            txtPhone.setText(xCompPhone.get().getValue());
        }
        
       
        
        try{
            String docPath = initialDataService.getDocPath();
            File dest = new File(docPath+File.separator+"logo.png");

            Image image = ImageIO.read(dest);
            if (image != null) {
                imgLogo.setIcon(new ImageIcon(image));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
     
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(!validateInputs()){
            return;
        }
        try{
            //clear
            var xComp = settingRepository.findByKey(Setting.COMPANY_NAME);
            if(xComp.isPresent()){
                settingRepository.delete(xComp.get());
            }
            var xCompAdd = settingRepository.findByKey(Setting.COMPANY_ADDRESS);
            if(xCompAdd.isPresent()){
                settingRepository.delete(xCompAdd.get());
            }
            var xCompPhone = settingRepository.findByKey(Setting.COMPANY_PHONE);
            if(xCompPhone.isPresent()){
                settingRepository.delete(xCompPhone.get());
            }
           
            Setting setting = new Setting();
            setting.setCreatedAt(TimeHelper.getCurrentTimestamp());
            setting.setKey(Setting.COMPANY_NAME);
            setting.setValue(txtCompanyName.getText());
            settingRepository.save(setting);

            Setting setting1 = new Setting();
            setting1.setCreatedAt(TimeHelper.getCurrentTimestamp());
            setting1.setKey(Setting.COMPANY_ADDRESS);
            setting1.setValue(txtAddress.getText());
            settingRepository.save(setting1);

            Setting setting2 = new Setting();
            setting2.setCreatedAt(TimeHelper.getCurrentTimestamp());
            setting2.setKey(Setting.COMPANY_PHONE);
            setting2.setValue(txtPhone.getText());
            settingRepository.save(setting2);
            

            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan. "+ex.getMessage());
        }

    }//GEN-LAST:event_btnSaveActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
