/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aldoapp.swingboot.gui.setting;

import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.entities.Role;
import com.aldoapp.swingboot.entities.Setting;
import com.aldoapp.swingboot.entities.User;
import com.aldoapp.swingboot.gui.ImageFileSelector;
import com.aldoapp.swingboot.helpers.TimeHelper;
import com.aldoapp.swingboot.repositories.RoleRepository;
import com.aldoapp.swingboot.repositories.SettingRepository;
import com.aldoapp.swingboot.repositories.UserRepository;
import com.aldoapp.swingboot.services.InitialDataService;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author aldo
 */
public class SettingsDlg extends javax.swing.JDialog {
    @Autowired
    UserRepository userRepository;
    
    @Autowired
    RoleRepository roleRepository;
    
    @Autowired
    SettingRepository settingRepository;
    
     
    @Autowired
    InitialDataService initialDataService;
    /**
     * Creates new form SettingsDlg
     */
    public SettingsDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
    }
    public static void showModal(String[] args) {
        
        SettingsDlg dialog = new SettingsDlg();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        //System.exit(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setting Awal");

        jLabel1.setText("Nama Perusahaan");

        txtCompanyName.setName("txtCompanyName"); // NOI18N

        jLabel2.setText("Alamat");

        txtAddress.setName("txtUsername"); // NOI18N

        jLabel3.setText("No Telp");

        txtPhone.setName("txtUsername"); // NOI18N

        jLabel4.setText("Logo");

        imgLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imgLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLogoMouseClicked(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Admin username");

        jLabel6.setText("Password");

        jLabel7.setText("Nama Lengkap");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(440, 440, 440))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPhone)
                                    .addComponent(txtCompanyName)
                                    .addComponent(txtAddress))
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 440, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(!validateInputs()){
            return;
        }
        try{
            //clear
            var xComp = settingRepository.findByKey(Setting.COMPANY_NAME);
            if(xComp.isPresent()){
                settingRepository.delete(xComp.get());
            }
            var xCompAdd = settingRepository.findByKey(Setting.COMPANY_ADDRESS);
            if(xCompAdd.isPresent()){
                settingRepository.delete(xCompAdd.get());
            }
            var xCompPhone = settingRepository.findByKey(Setting.COMPANY_PHONE);
            if(xCompPhone.isPresent()){
                settingRepository.delete(xCompPhone.get());
            }
            var xTax1 = settingRepository.findByKey(Setting.TAX_PERCENTAGE_1);
            if(xTax1.isPresent()){
                settingRepository.delete(xTax1.get());
            }
            var xTax2 = settingRepository.findByKey(Setting.TAX_PERCENTAGE_2);
            if(xTax2.isPresent()){
                settingRepository.delete(xTax2.get());
            }

            Setting setting = new Setting();
            setting.setCreatedAt(TimeHelper.getCurrentTimestamp());
            setting.setKey(Setting.COMPANY_NAME);
            setting.setValue(txtCompanyName.getText());
            settingRepository.save(setting);

            Setting setting1 = new Setting();
            setting1.setCreatedAt(TimeHelper.getCurrentTimestamp());
            setting1.setKey(Setting.COMPANY_ADDRESS);
            setting1.setValue(txtAddress.getText());
            settingRepository.save(setting1);

            Setting setting2 = new Setting();
            setting2.setCreatedAt(TimeHelper.getCurrentTimestamp());
            setting2.setKey(Setting.COMPANY_PHONE);
            setting2.setValue(txtPhone.getText());
            settingRepository.save(setting2);
            
             //https://stackoverflow.com/a/50515537/1225672
            String hash = BCrypt.hashpw(txtPassword.getText(),BCrypt.gensalt());

            User entity = new User();
            entity.setCreatedAt(TimeHelper.getCurrentTimestamp());
            entity.setFullName(txtFullname.getText());
            entity.setUsername(txtAdminUsername.getText());
            entity.setPassword(hash);
            var xrole = roleRepository.findById(Role.ADMIN);
            HashSet<Role> roles = new HashSet<Role>();
            roles.add(xrole.get());
            entity.setRoles(roles);
            User saved = userRepository.save(entity);
            if(saved!=null){            
                JOptionPane.showMessageDialog(null, "Data Tersimpan. Restart...");   
                System.exit(0);
            }else{
                JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan. "+ex.getMessage());
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void imgLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseClicked
        // TODO add your handling code here:
        try{
            File logoFile = ImageFileSelector.showDialog(null);
            if(logoFile==null){
                return;
            }
            String docPath = initialDataService.getDocPath();
            
            File dest = new File(docPath+File.separator+"logo.png");

            Files.copy(logoFile.toPath(), dest.toPath(), StandardCopyOption.REPLACE_EXISTING);


            Image image = ImageIO.read(dest);
            if (image != null) {
                imgLogo.setIcon(new ImageIcon(image));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_imgLogoMouseClicked
    private boolean validateInputs(){
        boolean res = true;
        
        List<String> errors = new ArrayList();
        if(txtCompanyName.getText().trim().length()==0){
            errors.add("Masukkan nama perusahaan");            
        }
        if(txtAddress.getText().trim().length()==0){
            errors.add( "Masukkan alamat perusahaan");            
        }
        if(txtPhone.getText().trim().length()==0){
            errors.add( "Masukkan telepon perusahaan");            
        }
        
        if(txtAdminUsername.getText().trim().length()==0){
            errors.add( "Masukkan username");            
        }
        if(txtFullname.getText().trim().length()==0){
            errors.add( "Masukkan nama lengkap");            
        }
        if(txtPassword.getText().trim().length()==0){
            errors.add( "Masukkan password");            
        }
        
        if(!errors.isEmpty()){
            JOptionPane.showMessageDialog(null, String.join("\n", errors));
            return false;
        }
        return res;
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAdminUsername;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
