/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.aprioricafe.gui.report;

import com.aldoapp.swingboot.BeanProvider;
import com.aldoapp.swingboot.helpers.RupiahHelper;
import com.aprioricafe.dto.SalesReportItem;
import com.aprioricafe.entities.SalesInvoice;
import com.aprioricafe.entities.SalesInvoiceItem;
import com.aprioricafe.repositories.SalesInvoiceItemRepository;
import com.aprioricafe.repositories.SalesInvoiceRepository;
import com.aprioricafe.services.PrintSalesReportService;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author aldo
 */
public class SalesReportDlg extends javax.swing.JDialog {
    @Autowired
    SalesInvoiceRepository salesInvoiceRepository;
    
    
    @Autowired
    SalesInvoiceItemRepository salesInvoiceItemRepository;
    
    @Autowired
    PrintSalesReportService printSalesReportService;
    
    List<SalesReportItem> reportItems = new ArrayList<>();
    /**
     * Creates new form SalesReportDlg
     */
    public SalesReportDlg() {
        BeanProvider.autowire(this); //use someRepository somewhere after this line.
        initComponents();
        setModal(true);
        Locale locale = new Locale("in", "ID");

        startDate.setLocale(locale);
        startDate.setDateToToday();
        
        endDate.setLocale(locale);
        endDate.setDateToToday();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startDate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel2 = new javax.swing.JLabel();
        endDate = new com.github.lgooddatepicker.components.DatePicker();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Transaksi Penjualan");

        jLabel1.setText("Dari Tanggal");

        jLabel2.setText("Sampai Tanggal");

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jLabel3.setText("Total");

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("0");
        lblTotal.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnPrint.setText("Cetak");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch)
                            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(jLabel3)
                    .addComponent(lblTotal))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadData();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try{
            printSalesReportService.generateAndPrint(reportItems);
        }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    public static void showModal(String[] args) {
        
        SalesReportDlg dialog = new SalesReportDlg();
        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.toFront();
        dialog.requestFocus();
        //System.exit(0);
    }
    
    private void loadData(){
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("No");
        tableModel.addColumn("No Nota");
        tableModel.addColumn("Menu");
        tableModel.addColumn("Tanggal");
        tableModel.addColumn("Total");
        Locale locale = new Locale("in", "ID");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy").withLocale(locale);
        
        reportItems.clear();
        
        var entities = salesInvoiceRepository.findAllByInvoiceDateBetween(startDate.getDate(), endDate.getDate());
        int no = 1;
        BigDecimal total = BigDecimal.ZERO;
        for (SalesInvoice entity : entities) {
            
            Vector row = new Vector();
            
            row.add(no);            
            row.add(entity.getInvoiceNo());    
            var invoiceItems = salesInvoiceItemRepository.findAllByInvoiceId(entity.getId());
            List<String> menus = new ArrayList<>();
            for(SalesInvoiceItem sii: invoiceItems){
                menus.add(sii.getMenu().getName());
            }
            row.add(String.join(", ", menus));
            String formattedDate = entity.getDate().format(formatter);
            row.add( formattedDate);
            row.add(RupiahHelper.formatRupiah(entity.getGrandTotal()));
            total = total.add(entity.getGrandTotal());
            
            tableModel.addRow(row);
            
            //report
            SalesReportItem sri = new SalesReportItem();
            sri.setInvoiceDate(formattedDate);
            sri.setInvoiceNo(entity.getInvoiceNo());
            sri.setMenus(String.join(", ", menus));
            sri.setTotal(RupiahHelper.formatRupiah(entity.getGrandTotal()));
            sri.setNo(String.valueOf(no));
            reportItems.add(sri);
            
            no++;
        }
        
        tbl.getColumnModel().getColumn(0).setPreferredWidth(27);

        tbl.setModel(tableModel);
        lblTotal.setText(RupiahHelper.formatRupiah(total));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private com.github.lgooddatepicker.components.DatePicker endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private com.github.lgooddatepicker.components.DatePicker startDate;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
